version: 0.2

env:
  variables:
    FLASK_APP: "flaskerino/__init__.py"
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -e .
  pre_build:
    commands:
      - python flaskerino/tests/test_index.py -v
  build:
    commands:
      - echo Entered the build phase...
